# Terminal stuff
cask "alacritty"
brew "fish"
cask "font-caskaydia-cove-nerd-font"
brew "helix"
brew "starship"
brew "zellij"

# Package managers
brew "node"
brew "mise"
brew "pipx"

# Git
brew "gh"
brew "git"
brew "gitui"

# LSP
brew "cfn-lint"
brew "marksman"
brew "ruff"
brew "taplo"
brew "yaml-language-server"

# Window manager
cask "rectangle"

# Docker
brew "colima"
brew "docker"
brew "docker-buildx"
brew "docker-completion"
brew "docker-compose"
brew "docker-credential-helper"

# Tools
brew "bacon"
brew "bat"
brew "dust"
brew "eza"
brew "fzf"
brew "jq"
brew "ripgrep"
brew "stow"
brew "usage"  # required by mise

# Include local Brewfile if present
local_file = File.join(ENV["HOME"], "/.config/brew/local/Brewfile")
if File.file?(local_file) then
  instance_eval(File.read(local_file))
end
