import = ["/Users/timothy.may/.config/alacritty/themes/catppuccin-mocha.toml"]

[font]
size = 12.0

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[window]
option_as_alt = "OnlyLeft"
